# Generated by Django 4.2.7 on 2024-06-14 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_attendance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated',
            field=models.DateField(default=datetime.date(2024, 6, 14)),
        ),
    ]
