# Generated by Django 4.2.7 on 2024-06-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_attendance_status_attendance_updated_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='No_of_classes_attended',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='no_of_classes_occurred',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(related_name='attandance_data', to='API.attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to='API.student'),
        ),
    ]
