# Generated by Django 4.2.7 on 2024-06-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_subject_no_of_classes_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='no_of_classes_occured',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
